services:
  - type: web
    name: tts-waifu
    env: node
    plan: free
    nodeVersion: 18
    buildCommand: "echo 'no build'"
    startCommand: "node server.js"
    autoDeploy: true
    healthCheckPath: "/health"
