services:
  - type: web
    name: tts-waifu
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    healthCheckPath: "/health"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
