services:
  - type: web
    name: tts-waifu
    env: node
    plan: free
    buildCommand: "echo 'no build'"
    startCommand: "node server.js"
    autoDeploy: true
    healthCheckPath: "/health"
    envVars:
      - key: NODE_VERSION
        value: 18
